### ISSUE TITLE
Live reloading 

### ISSUE THREAD

**Issue by suchcodemuchwow** [jsynowiec/node-typescript-boilerplate#12]
First I just want to thank you for providing this kind of work. I am pretty new in typescript and I am practising in the environment. I just wanted to make things work like in vanilla javascript that's why I used nodemon for live reloading. There are build commands which compile typescript to javascript in npm scripts but are there any option for vscode to run compiled program in development server. I used 
`npm run build:watch` in the first terminal and in second one `nodemon /build/src/main.js` it is working but I just want to be sure is that the way you are working or are there any downside of this approach, thanks.

**Comment by jsynowiec** [comment]
There are many solutions to this - you can keep using nodemon and tsc:watch, it's OK. You can also configure vscode to run complie tasks and start server using tasks. You can red more in the [vscode docs](https://code.visualstudio.com/Docs/editor/tasks).
