### ISSUE TITLE
Running npm run test hangs

### ISSUE THREAD

**Issue by masimplo** [jsynowiec/node-typescript-boilerplate#14]
It seems that jest is hanging for some reason on the current version of the repo.

I am using node v10.15.3 and npm 6.4.1

**Comment by jsynowiec** [comment]
Thanks for reporting. I need more info because it works for me just fine.
![Screenshot 2019-05-21 at 08 54 40](https://user-images.githubusercontent.com/1029142/58074691-278f4880-7ba6-11e9-8740-8e66e1cd8eb3.png)

**Comment by masimplo** [comment]
I clone the repo, do `npm i`, run `npm t` and it hangs.
![Screenshot 2019-05-21 10 00 16](https://user-images.githubusercontent.com/803983/58075051-54942900-7baf-11e9-9737-c8b6b673da3f.png)

I really don't know what else might be different. What would you like me to check?
MacOS 10.14.4
Node 10.15.3
Npm 6.4.1

Global packages:
- @angular/cli@7.3.8
- cordova@8.0.0
- ionic@4.12.0
- npm@6.4.1

PS: Also tried installing dependencies with Yarn instead, but same thing happens.

**Comment by jsynowiec** [comment]
Sorry, but I can't reproduce it. I did a clean clone/install and it finishes just fine. The only difference I see is that I have npm 6.9.0

**Comment by masimplo** [comment]
It looks that this is an issue with jest and not your repo in particular. Sorry for the confusion, but I thought it was some configuration issue as I have successfully used jest in the past in other projects.

[Issue link](https://github.com/facebook/jest/issues/4529)

Fix: `brew uninstall watchman`

Thanks for looking into this.
