### ISSUE TITLE
Change "TSLint" in the repository description to "ESLint".

### ISSUE THREAD

**Issue by KoutaKawase** [jsynowiec/node-typescript-boilerplate#26]
![image](https://user-images.githubusercontent.com/37544784/87965343-8d52c980-caf6-11ea-9a6d-9dd112a07eea.png)

"TSLint" in the repository description has not been replaced by "ESLint".

I couldn't figure out how to change this in a pull request.😥

Thank you.

**Comment by KoutaKawase** [comment]
The same goes for "tslint" tag.

**Comment by jsynowiec** [comment]
Thanks! Changed.
