### ISSUE TITLE
Jest issue

### ISSUE THREAD

**Issue by whoisdominic** [jsynowiec/node-typescript-boilerplate#36]
When I use the boilerplate and try and add and import statement it throws an error in jest

SyntaxError: Cannot use import statement outside a module

![Screen Shot 2022-04-03 at 3 13 14 PM](https://user-images.githubusercontent.com/32504814/161450995-7526674b-dff8-462f-9085-e8305719d162.png)

**Comment by jsynowiec** [comment]
Please read [this](https://github.com/jsynowiec/node-typescript-boilerplate#es-modules) first. If you have problems with Jest, check the [Jest](https://jestjs.io/docs/ecmascript-modules) and the [ts-jest](https://kulshekhar.github.io/ts-jest/docs/next/guides/esm-support/) transformed docs. Also, you can checkout one of the earlier tags if you do not want ESM, and keep using CommonJS instead.

Regarding `chalk`, please read their [v5](https://github.com/chalk/chalk/releases/tag/v5.0.0) release notes - it mentions that you should probably stay on v4 in this case.

The following code works fine when added to the unit test and use `chalk@v4`.

```ts
import * as chalk from 'chalk';

console.log(chalk.bgCyan('hello'));
```

```
npm run test

> node-typescript-boilerplate@0.0.0 test
> jest --coverage

  console.log
    hello
```

**Comment by danwt** [comment]
Did you get it solved @[whoisdominic](https://github.com/whoisdominic)?

**Comment by elliotsayes** [comment]
@danwt 
`tsconfig.json`:
```json
{
  "compilerOptions": {
    ...
    "esModuleInterop": true,
    ...
  }
}
```
Fixes most of the annoying BS for me. 

@jsynowiec Really not sure why this isn't the default. No one wants to waste time reading 100 pages of documentation to understand what is going on...
