### ISSUE TITLE
What is `tsutils` ?

### ISSUE THREAD

**Issue by Seblor** [jsynowiec/node-typescript-boilerplate#37]
I see that the package.json includes `tsutils` as a dev dependency, but even after reading the module's README, I have no idea what is does.

And since I don't see it being used / imported anywhere in the project, I've been wondering what it was used for ?

**Comment by jsynowiec** [comment]
It is a library with utility functions for working with TypeScript's AST. It is used, for example, by ESLint. It might be redundant to keep it in the package.json, but I've seen some conflicts in the past and decided to pin the version to a working one.
