### ISSUE TITLE
After building, import file using relative path show module not found error

### ISSUE THREAD

**Issue by Giancarlo-Ma** [jsynowiec/node-typescript-boilerplate#38]
nodejs can not resolve file using esm without file extention, how to resolve this problem

**Comment by jsynowiec** [comment]
ES modules relative import paths need to use extensions. See [this](https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/#esm-nodejs).

Please do not open issues for questions regarding CommonJS or ESM on this repo.
