### ISSUE TITLE
vscode configuration

### ISSUE THREAD

**Issue by Tallyb** [jsynowiec/node-typescript-boilerplate#4]
Hi, 
Can you add your vscode settings and launch to git? Do you have a debug and tests - debug configurations you can share ?
Great repo!

**Comment by jsynowiec** [comment]
Thanks!

I want to keep this as much editor/IDE independent as possible so I don't think adding my `.vscode` folder is a good idea. I can share my tasks and launch configuration as a gist if you like though. Do you need anything in particular?

**Comment by Tallyb** [comment]
Thanks. I would like to see the debug and tests debug configs in the
launch. Can you share them?

**Comment by jsynowiec** [comment]
I'm not using such configs for this boilerplate project, but I'll share some samples from my other projects later.

**Comment by jsynowiec** [comment]
**launch.json**
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Debug",
      "cwd": "${workspaceRoot}",
      "program": "${workspaceRoot}/src/main.ts",
      "sourceMaps": true,
      "outFiles": ["${workspaceRoot}/build/**/*.js"],
      "preLaunchTask": "build",
      "stopOnEntry": true,
      "console": "internalConsole"
    }
  ]
}
```

**tasks.json**
```json
{
  "version": "0.1.0",
  "command": "npm",
  "isShellCommand": true,
  "showOutput": "always",
  "suppressTaskName": true,
  "tasks": [
    {
      "taskName": "build",
      "args": ["run", "build"],
      "isBuildCommand": true
    },
    {
      "taskName": "test",
      "args": ["run", "test"]
    }
  ]
}
```
