### ISSUE TITLE
Remove tsutils

### ISSUE THREAD

**Issue by Darter90** [jsynowiec/node-typescript-boilerplate#44]
Hello there.

I noticed that your project contains **tsutils**; this library hasn't been maintained for a year now, creating problems to others libraries like **typescript-eslint**. 

Check this discussion link [here](https://github.com/typescript-eslint/typescript-eslint/issues/5552) and evaluate to remove it and clean your NPM dependencies.

Best regards and thanks for your work.

**Comment by jsynowiec** [comment]
Thanks. I am monitoring this, and a few other similar issues regarding tsutils. However, as you can see, the issue you linked is still open and a relevant PR porting the functionality to type-utils is still in a Draft state. There is currently no suitable alternative.

> creating problems to others libraries like typescript-eslint.

How npm resolves and installs dependencies, there should be no conflict with other libraries.

I am going to close this issue as non-actionable (presently) to keep it out of my queue. But keep commenting if you have any alternatives or suggestions.
