### ISSUE TITLE
Discussing plan to use renovate bot to update dependencies

### ISSUE THREAD

**Issue by JokeJason** [jsynowiec/node-typescript-boilerplate#49]
Hi, do you have any plan to update dependencies automatically using [renovate bot](https://github.com/renovatebot/renovate)? It's free for github repos.

**Comment by jsynowiec** [comment]
No, I do not. This is a template repository, not a dependency package. An example, that helps to bootstrap a new project. When using it, you are supposed to decide on your own which packages and versions you are going to use in a project that you are building.

I tend to bump dependencies with every TypeScript upgrade. But, more as a convenience, ensuring that the source's build and the example tests run.
