### ISSUE TITLE
npm run lint doesn't work on windows

### ISSUE THREAD

**Issue by eugenious** [jsynowiec/node-typescript-boilerplate#5]
When running on Windows I found two problems with tslint, with pretty easy fixes:

1. single quotes can't be used

Easy fix in package.json:
BEFORE:

    "lint": "tslint -t stylish --type-check --project 'tsconfig.json'",

AFTER:

    "lint": "tslint -t stylish --type-check --project \"tsconfig.json\"",

2. CRLF causing linting errors

Easy fix in tslint.json
ADD:

    "linebreak-style": false

Sigh, windows...

**Comment by jsynowiec** [comment]
Thank you for reporting. I don't have Windows to test this so I'm going to fix it on a separate branch and ask you to validate before merging.

**Comment by eugenious** [comment]
I will be happy to do that. Thank you for a great project.

**Comment by jsynowiec** [comment]
@eugenious I've read about `linebreak-style` check and I'm against setting it to `false` as the default for this starter. Line breaks should be consistent in source files.

If you're mixing CRLFs with LFs, then in my opinion you should correct those files and settle for one style with either `"linebreak-style": [true, "LF"]` or `"linebreak-style": [true, "CRLF"]`.

**Comment by jsynowiec** [comment]
@eugenious Please check if https://github.com/jsynowiec/node-typescript-boilerplate/pull/7 fixes `npm run lint` on Windows.

**Comment by eugenious** [comment]
Ah the fun of platform line endings.

The issue is, some people (including me) have the setting for git line endings doing automatic conversions to CRLF on Windows.

I have revisited my decision and now I have git settings to checkout line endings as LF no matter what, which seems like a saner way to go.

**Comment by jsynowiec** [comment]
Git can handle line endings by auto-converting CRLF into LF when you add a file to the index, and vice versa when it checks out code onto your filesystem. You can enable this with the `core.autocrlf` setting. 

On Windows, set it to `true` – this converts LF endings into CRLF on checkout

```
$ git config --global core.autocrlf true
```

On Mac and Linux you may want Git to fix files with CRLF endings that were accidentally introduced. To convert CRLF to LF on commit but not the other way around, set `core.autocrlf` to `input`

**Comment by eugenious** [comment]
Yes I know, and that's exactly the problem!

By setting core.autocrlf to true, projects will be cloned into Windows with CRLF.

And running "npm run lint" locally on Windows will fail, as it expects line endings to be LF, not CRLF.

**Comment by jsynowiec** [comment]
I still think that enforcing unified line endings across files is a safe default option (and a desired one). It's possible to opt-out - disable this setting or change it to `CRLF` if you want to.

**Comment by eugenious** [comment]
I think I'm still not being clear enough.

Unified line endings across files is normal and expected.

Unified line endings across PLATFORMS, for the same git repository, isn't a universal practice.

Anyway, for this issue it's not such a problem. I've adopted the practice of now of using only `LF` everywhere, and probably this is what everybody _should_ be doing.
