### ISSUE TITLE
tsconfig is turning off some compiler checks

### ISSUE THREAD

**Issue by pablocar80** [jsynowiec/node-typescript-boilerplate#64]
The tsconfig file is turning off some compiler checks. The following features are disabled:

    "noImplicitAny": false,
    "noImplicitThis": false,
    "strictNullChecks": false

**Comment by jsynowiec** [comment]
I don't know whether this is a question or a request to change these defaults, or just an observation. Regardless, I will give you some additional context: turning on these checks is generally not a good idea, as it is cumbersome to handle for someone learning TypeScript. TypeScript developers disagree about whether these checks should be enabled or disabled. There is no correct answer here. However, having them disabled is usually the safer default.

You can change these options to your preference in your project.
